---

- hosts: zero_test
  vars:
    user: acain
    user_group: domain^users
########## vars for install #########
    installer: splunk-6.5.1612-a8914247a786-linux-2.6-x86_64.rpm
    url: 'http://releases.splunk.com/released_builds/6.5.1612/splunk/linux/splunk-6.5.1612-a8914247a786-linux-2.6-x86_64.rpm'
########## vars for apps ##########
#    deploy_dir: apps
    deploy_dir: apps
    app_packages:
########## Apps for all search heads #########
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: 'GEN-STG_SEARCH', target: 'search' }
########## Apps for all installs #########
      - { project: 'zero-id', repo: 'zero_prod', branch: 'master', target: 'all' }
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'master', target: 'all' }
########## Apps for SHC deployer #########
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: 'SHOWCASE_DP', target: 'shc-deployer' }
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'shc-deployer' }
########## Apps for SHC members #########
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: 'SHOWCASE_SH', target: 'shc-member' }
      - { project: 'zero-id', repo: '01-gold_shc', branch: 'master', target: 'shc-member' }
      - { project: 'zero-id', repo: '01-rolemap_perm', branch: 'master', target: 'shc-member' }
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'non-ssl', target: 'shc-member' }
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master', target: 'shc-member' }
########## Apps for dev search #########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'dev-sh' }
########## Apps for prod search #########
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'master', target: 'prd-sh' }
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master', target: 'prd-sh' }
########## Apps for IDX slaves #########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'idx-slave' }
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: 'master', target: 'idx-slave' }
########## Apps for IDX master #########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'idx-cm' }
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: 'master', target: 'idx-cm' }
########## Apps for DCNs ###########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'dcn' }
########## Apps for HFs ###########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'hf' }
########## vars for auth ##########
#    dev_group: SG-IT-SplunkZero-PERM-appinspect-DEV
#    pwr_group: SG-IT-SplunkZero-PERM-appinspect-PWR
#    usr_group: DG-IT-SplunkZero-PERM-appinspect-USR
# this variable is the AD group modifier for search head perms
#    team: sgs
#    okta_domain: splunk.okta.com
#    okta_chic_key: splunkinc_splunkzeroglobalsecurityes_1/exk1cu1bfzja1dtXL1d8
#    uri: configured in host file
  become: yes
  roles:
    - splunk-update
    - splunk-CHG-dftpass
    - configure_open_ports
    - splunk_gen_conf-lic-slave
    - { role: splunk_gen_conf_auth-saml, when: spl_role == 'prd_sh' }
    - configure_THP
    - configure_file-descriptors
    - configure_git-management
    - splunk_gen_update-repo-apps
    - configure_shell_user_nopass
#    - { role: configure_shell_access, when: spl_role == 'dev_sh' }
#    - splunk_sh_conf_dev-sh
    - { role: splunk_shc_init, when: (spl_role is defined and (spl_role == 'shc_cap' or spl_role == 'shc_mem')) }
    - splunk_gen_restart
    - { role: splunk_shc_cap_election, when: spl_role == 'shc_cap' }
    - { role: splunk_shc_add-member, when spl_role == 'shc_mem' }


# - include: splunk_sh_add_search-peers-srv_mon.yml
#   vars:
#     uri: https://sv-prd-splx-903.sv.splunk.com
#     mgmt_port: 8089

#- include: splunk_sh_install-itsi.yml
